### ISSUE TITLE
Barebones branch does not seem up to date

### ISSUE THREAD

**Issue by PrasadBabarendaGamage** [OpenCMISS-Examples/template_example#2]
Hugh, should we be using the barebones branch? (from first paragraph of the OpenCMISS-Examples/template_example  README.rst) It seems to be missing the docs.

**Comment by hsorby** [comment]
The barebones branch is perhaps too barebones for your liking.  I will add the docs if no one thinks that the current minimum barebones is correct.

**Comment by hsorby** [comment]
Having had a think about this I would like to keep this branch as is, that is without adding the documentation.  I think another branch with the full template (i.e. with the docs) should be created for those who are creating a tutorial style example.

**Comment by hsorby** [comment]
I have added a tutorial branch for those wanting to do more detailed documentation.
