### ISSUE TITLE
Example does not build

### ISSUE THREAD

**Issue by PrasadBabarendaGamage** [OpenCMISS-Examples/template_example#4]
`psam012@bn369532:~/opt/OpenCMISS-convert-examples/new-examples/uniaxial_extension_build$ cmake -DOpenCMISSLibs_DIR=/home/psam012/opt/OpenCMISS/main/opencmiss/in
stall ../uniaxial_extension
-- The C compiler identification is GNU 5.4.0
-- The Fortran compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- FindMPI wrapper: System search enabled
-- FindMPI wrapper: Trying to find version  on system in MODULE mode
-- Verifying MPI C Compiler Compatibility: /usr/bin/mpicc
-- Verifying MPI Fortran Compiler Compatibility: /usr/bin/mpif90
-- Performing Test MPI_Fortran_MODULE_COMPATIBLE
-- Performing Test MPI_Fortran_MODULE_COMPATIBLE - Success
-- Looking for OpenCMISS-Iron ...
-- FindBLAS wrapper: System search enabled
-- FindBLAS wrapper: Trying to find version 3.5.0 on system in MODULE mode
-- Looking for Fortran dgemm
-- Looking for Fortran dgemm - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- FindBLAS wrapper: Found: /usr/lib/libf77blas.so;/usr/lib/libatlas.so
-- FindZLIB wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- FindBZip2 wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- FindPASTIX wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- FindLAPACK wrapper: System search enabled
-- FindLAPACK wrapper: Trying to find version  on system in MODULE mode
-- A library with BLAS API found.
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- FindLAPACK wrapper: Found: /usr/lib/liblapack.so;/usr/lib/libf77blas.so;/usr/lib/libatlas.so
-- FindSCALAPACK wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- FindPARMETIS wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- FindMUMPS wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- FindSUITESPARSE wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- FindSUPERLU wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- FindSUNDIALS wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- FindHYPRE wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- FindSUPERLU_DIST wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- FindPETSC wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- FindLLVM wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- FindLibXml2 wrapper: System search enabled
-- FindLibXml2 wrapper: Trying to find version 2.7.6 on system in MODULE mode
-- FindLibXml2 wrapper: Found: /usr/lib/x86_64-linux-gnu/libxml2.so
-- FindClang wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- FindCSim wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- Looking for OpenCMISS-Iron ... Success
-- Looking for OpenCMISS-Zinc ...
-- FindFreetype wrapper: System search enabled
-- FindFreetype wrapper: Trying to find version  on system in MODULE mode
-- FindFreetype wrapper: Found: /usr/lib/x86_64-linux-gnu/libfreetype.so
-- FindFTGL wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- FindOPTPP wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- FindGLEW wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- FindNETGEN wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- FindGDCM-ABI wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- FindPNG wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- FindJPEG wrapper: System search enabled
-- FindJPEG wrapper: Trying to find version  on system in MODULE mode
-- FindJPEG wrapper: Found: /usr/lib/x86_64-linux-gnu/libjpeg.so
-- FindTIFF wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- FindImageMagick wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- FindITK wrapper: Found at /home/psam012/opt/OpenCMISS/main/opencmiss/install/cmake in CONFIG mode
-- Looking for OpenCMISS-Zinc ... Success
-- Configuring done
CMake Error in src/fortran/CMakeLists.txt:
  No known features for CXX compiler

  "

-- Generating done
-- Build files have been written to: /home/psam012/opt/OpenCMISS-convert-examples/new-examples/uniaxial_extension_build
psam012@bn369532:~/opt/OpenCMISS-convert-examples/new-examples/uniaxial_extension_build$ cmake --build .
Scanning dependencies of target uniaxial_extension
[ 50%] Building Fortran object src/fortran/CMakeFiles/uniaxial_extension.dir/uniaxial_extension.F90.o
make[2]: *** No rule to make target 'mpi-NOTFOUND', needed by 'src/fortran/uniaxial_extension'.  Stop.
CMakeFiles/Makefile2:85: recipe for target 'src/fortran/CMakeFiles/uniaxial_extension.dir/all' failed
make[1]: *** [src/fortran/CMakeFiles/uniaxial_extension.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by PrasadBabarendaGamage** [comment]
This seems to be because the cmake files in this repo are not the latest versions. The (newer) cmake files in https://github.com/OpenCMISS-Examples/diffusion_equation work fine.

**Comment by hsorby** [comment]
I have updated the documentation to have the correct target link libraries.
